#!/usr/bin/env bash
# Fixes the issue with the server
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::]:?8080) /\180 /' /etx/nginx/sites-enabled/default
pkill apache2
su nginix -s /bin/bash -c 'service nginx restart'
